package io.scoresby.backend.dao;

public class Artist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Artist.ArtistId
     *
     * @mbggenerated Fri May 20 09:27:02 CEST 2022
     */
    private Integer artistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Artist.Name
     *
     * @mbggenerated Fri May 20 09:27:02 CEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Artist.ArtistId
     *
     * @return the value of Artist.ArtistId
     *
     * @mbggenerated Fri May 20 09:27:02 CEST 2022
     */
    public Integer getArtistId() {
        return artistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Artist.ArtistId
     *
     * @param artistId the value for Artist.ArtistId
     *
     * @mbggenerated Fri May 20 09:27:02 CEST 2022
     */
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Artist.Name
     *
     * @return the value of Artist.Name
     *
     * @mbggenerated Fri May 20 09:27:02 CEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Artist.Name
     *
     * @param name the value for Artist.Name
     *
     * @mbggenerated Fri May 20 09:27:02 CEST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}